"""Japanese strings for deck.py: every English string the deck draws, mapped to its translation.

deck.py stops with an error if it meets an English string that has no entry here, so a new or changed
string on a slide must be added before the Japanese edition can build.
"""

J = {
    'The ai/ harness · ProductionManagementAI': 'ai/ ハーネス · ProductionManagementAI',
    'The ai/ harness': 'ai/ ハーネス',
    'How Claude and Codex share one process: structure, routing, skills, gates and principles': 'Claude と Codex が 1 つの手順を共有するしくみ：構成、振り分け、スキル、関門、原則',
    'How Claude and Codex share one file-based process — what each part does, how a request flows through it, and why it is built this way.': 'Claude と Codex が 1 つのファイルベースの手順を共有するしくみ — 各部分の役割、依頼がたどる流れ、そしてこの形にした理由。',
    'Source: ai/harness-overview.md, as of 2026-09-23 · Reference, not a source of authorization — ai/policies.md remains the authority.': '出典：ai/harness-overview.md（2026-09-23 時点）· 参照資料であり権限の根拠ではない — 権限は引き続き ai/policies.md が定める。',
    '01 · Why it exists': '01 · 存在する理由',
    'Two agents, many sessions, no shared memory': '2 つのエージェント、多数のセッション、共有されない記憶',
    'Claude and Codex both work on this repository, often in different sessions. Without a shared, file-based source of instructions, each session would re-derive — or silently disagree about — the things that matter.': 'このリポジトリでは Claude と Codex の両方が、多くの場合別々のセッションで作業する。ファイルに基づく共通の指示がなければ、各セッションは重要な事柄を導き直すか、気づかないまま食い違ってしまう。',
    'Scope': '範囲',
    'What is in and out of this piece of work': 'この作業に含まれるものと含まれないもの',
    'Technology choices': '技術選定',
    'What the project has actually decided vs. what is still open': 'プロジェクトが実際に決めたことと、まだ未決のこと',
    'Quality bar': '品質基準',
    'What “correct” and “done” mean for each kind of change': '変更の種類ごとの「正しい」と「完了」の意味',
    'Authorization': '権限',
    'What an agent may do alone, and when it must stop and ask': 'エージェントが単独でできること、止まって確認すべきとき',
    'THE HARNESS’S JOB': 'ハーネスの役割',
    'A request plus the repository’s own files should be enough for any agent, in any session, to pick up correct, consistent work — without reading prior chat history.': '依頼とリポジトリ自身のファイルがあれば、どのエージェントでも、どのセッションでも、過去のチャット履歴を読まずに正しく一貫した作業を引き継げること。',
    'Context is made **durable** (in files) and **agent-neutral** (one source both agents read).': '文脈を**永続的**（ファイルに）かつ**エージェント非依存**（両者が読む 1 つの原本）にする。',
    '02 · Anatomy': '02 · 構成',
    'What lives in ai/ — and why each part exists': 'ai/ にあるもの — 各部分が存在する理由',
    'project.md': 'project.md',
    'Confirmed vs. open technology decisions': '確定した技術判断と未決の技術判断',
    'No agent invents or assumes a choice the project hasn’t made': 'プロジェクトが決めていない選定を、エージェントが作ったり仮定したりしない',
    'policies.md': 'policies.md',
    'Authorization, plan approval, pause conditions, untrusted-content guardrails': '権限、計画の承認、一時停止の条件、信頼できない内容への対策',
    'The safety boundary: act alone, or stop and ask': '安全の境界：単独で行うか、止まって確認するか',
    'rules/ · 8 files': 'rules/ · 8 ファイル',
    'common, documentation, frontend, backend, database, testing, git-review, ci-cd': 'common、documentation、frontend、backend、database、testing、git-review、ci-cd',
    'One current standard per area, applied by every skill': '領域ごとに 1 つの現行基準を、すべてのスキルが適用する',
    'workflows/ · 4': 'workflows/ · 4',
    'bootstrap, feature-delivery, bug-fix, harness-improvement': 'bootstrap、feature-delivery、bug-fix、harness-improvement',
    'A starting sequence for each way work begins': '作業の始まり方ごとの出発点となる手順',
    'skills/ · 13': 'skills/ · 13',
    'The “how to do X” procedures': '「X をどう行うか」の手順',
    'Bounded, checkable units with one 8-part shape': '範囲が決まり確認できる単位。8 部構成で共通',
    'templates/': 'templates/',
    'Starting document for every skill output': '各スキルの成果物の出発点となる文書',
    'Modeled on real formats (MADR, IEEE 829, 基本設計書 …)': '実在する形式に倣う（MADR、IEEE 829、基本設計書 …）',
    'checklists/ · 4': 'checklists/ · 4',
    'Point-in-time pass/fail gates': 'その時点での合否の関門',
    '“Did I follow the rules” becomes an explicit check': '「ルールに従ったか」を明示的な確認にする',
    'evaluations/': 'evaluations/',
    'Manual scenarios: process rules and adversarial cases': '手動のシナリオ：手順のルールと攻撃的なケース',
    'Guidance changes are tested, not trusted on faith': '指針の変更は信頼ではなくテストで確かめる',
    'improvements/': 'improvements/',
    'One record per harness change': 'ハーネス変更ごとに 1 つの記録',
    'Keeps the history of why the harness changed': 'ハーネスがなぜ変わったかの履歴を残す',
    '03 · Separation of concerns': '03 · 関心の分離',
    'Three different questions, three different places': '3 つの異なる問い、3 つの異なる場所',
    'Collapsing them would bury authorization inside technical detail — or turn every rule into an unenforced suggestion.': '1 つにまとめると、権限が技術的な詳細に埋もれるか、すべてのルールが確認の機会のない提案になってしまう。',
    'Is this agent allowed to do this, or must it stop and ask?': 'このエージェントはこれを行ってよいか、それとも止まって確認すべきか？',
    'Plan approval, pause conditions, external operations (push, PR, merge, deploy), untrusted content is data — never instructions.': '計画の承認、一時停止の条件、外部操作（push、PR、マージ、デプロイ）、信頼できない内容はデータであり指示ではない。',
    'What does correct look like for this kind of change?': 'この種の変更で正しい形はどうあるべきか？',
    'RFC 9457 errors, strict TypeScript, parameterized SQL, WCAG 2.2 AA, SHA-pinned actions, test-pyramid shape …': 'RFC 9457 のエラー、厳格な TypeScript、パラメーター化 SQL、WCAG 2.2 AA、SHA 固定のアクション、テストピラミッド …',
    'Right now, before the next step — did I actually meet that bar?': '今、次のステップの前に、その基準を実際に満たしたか？',
    'design-consistency, security-review, delivery, release-readiness: explicit gates at the moment they matter.': 'design-consistency、security-review、delivery、release-readiness：必要な瞬間の明示的な関門。',
    '04 · Routing': '04 · 振り分け',
    'How a request actually flows — for either agent': '依頼が実際にたどる流れ — どちらのエージェントでも',
    'Every task enters through the same chain. The sequence matters: each step narrows what the next one reads.': 'すべての作業は同じ流れで始まる。順序に意味があり、各ステップが次に読むものを絞り込む。',
    'Entry point': '入口',
    '`AGENTS.md` (shared). `CLAUDE.md` is a thin adapter that points at it — never duplicates it.': '`AGENTS.md`（共通）。`CLAUDE.md` はそれを指す薄い接続部分で、内容を複製しない。',
    'Always read first': '最初に必ず読む',
    '`project.md`, `policies.md`, `rules/common.md`.': '`project.md`、`policies.md`、`rules/common.md`。',
    'Pick a workflow': 'ワークフローを選ぶ',
    'bootstrap · feature-delivery · bug-fix · harness-improvement.': 'bootstrap · feature-delivery · bug-fix · harness-improvement。',
    'Pick skill(s)': 'スキルを選ぶ',
    '`skills/README.md` routes to a `SKILL.md`, read directly (no auto-discovery).': '`skills/README.md` が `SKILL.md` に振り分け、直接読む（自動検出なし）。',
    'Start from a template': 'テンプレートから始める',
    'Every skill output begins from `ai/templates/`.': '各スキルの成果物は `ai/templates/` から始める。',
    'Pass the checklist': 'チェックリストに合格する',
    'The skill names the gate it must pass at that point.': 'スキルがその時点で合格すべき関門を示す。',
    'Record durable state': '永続的な状態を記録する',
    '`status.md`, `decisions.md`, `evidence.md` in `work-items/<WI-###>/`.': '`work-items/<WI-###>/` の `status.md`、`decisions.md`、`evidence.md`。',
    '**Outside the per-task chain:** `ai/evaluations/` is how the harness checks itself — run when a change to shared guidance is proposed. Step 7 is what makes work resumable: the next step, possibly another agent in another session, continues from the repository, not from the chat.': '**作業ごとの流れの外：** `ai/evaluations/` はハーネスが自分自身を確認するしくみで、共有の指針の変更が提案されたときに実行する。ステップ 7 が作業を再開可能にする：次のステップは、別のセッションの別のエージェントかもしれないが、チャットではなくリポジトリから続ける。',
    '05 · Workflows': '05 · ワークフロー',
    'Four ways work begins, four starting sequences': '作業の 4 つの始まり方、4 つの出発点の手順',
    'Each workflow orders the skills a task needs and ends with an explicit exit condition — without hard-coding every path.': '各ワークフローは作業に必要なスキルを順に並べ、明示的な終了条件で終わる — すべての道筋を固定はしない。',
    'Confirm open tech decisions and demo scope': '未決の技術判断とデモの範囲を確認',
    'Plan: skeleton, local env, CI checks': '計画：骨組み、ローカル環境、CI の確認',
    'Build in bounded, approved steps': '範囲の決まった承認済みのステップで構築',
    'Verify real commands; update project.md': '実際のコマンドを検証し project.md を更新',
    'Record gaps; hand off to feature-delivery': '不足を記録し feature-delivery に引き継ぐ',
    'Brief + acceptance criteria': '要件と受け入れ基準',
    'Plan, shown and approved': '計画を示し、承認を得る',
    'Architecture check → BD / DB / API / DD': 'アーキテクチャ確認 → BD / DB / API / DD',
    'Reconcile designs, then implement': '設計を突き合わせてから実装',
    'Unit/integration, then system/E2E': '単体・結合、次にシステム・E2E',
    'Review diff, PR within authorization': '差分をレビューし、権限内で PR',
    'Record evidence': '証跡を記録',
    'Reproducible failing vs. expected case': '失敗と期待の動作を再現できるケース',
    'Severity: live incident mitigates first': '重大度：稼働中の障害はまず緩和',
    'Find cause; add a regression check': '原因を見つけ、回帰の確認を追加',
    'Fix; update affected design/contracts': '修正し、影響する設計・契約を更新',
    'Targeted checks; record evidence': '対象の確認を実行し、証跡を記録',
    'Blameless postmortem if live': '稼働中なら責めない事後分析',
    'Record observed failure / change': '観察した失敗・変化を記録',
    'Propose the smallest useful change': '最小の有益な変更を提案',
    'Evaluate with ai/evaluations cases': 'ai/evaluations のケースで評価',
    'Record limits; review before adoption': '限界を記録し、採用前にレビュー',
    'Rollback via version control — never relax a gate': 'バージョン管理でロールバック — 関門は緩めない',
    '06 · Skills': '06 · スキル',
    '13 skills, composed as a resumable hand-off chain': '13 のスキルを、再開できる引き継ぎの連鎖として組み合わせる',
    'A workflow picks the subset a task needs. Each skill’s step 8 hands its artifact to the next — the chain survives agent and session switches.': 'ワークフローが作業に必要なものを選ぶ。各スキルのステップ 8 が成果物を次に渡すため、エージェントやセッションが替わっても連鎖は途切れない。',
    'plan.md · approved': 'plan.md · 承認済み',
    'brief.md · REQ-###': 'brief.md · REQ-###',
    'ADR · STRIDE': 'ADR · STRIDE',
    'BD · Mermaid · SVG': 'BD · Mermaid · SVG',
    '###_DB': '###_DB',
    'TC-### · evidence': 'TC-### · 証跡',
    'branch · src/ · tests/': 'ブランチ · src/ · tests/',
    'BD/DD sections': 'BD/DD の節',
    'DD + API/FN/SPD · mockup': 'DD + API/FN/SPD · モックアップ',
    'review.md': 'review.md',
    'review / evidence': 'review / evidence',
    '.github/workflows': '.github/workflows',
    'improvement.md → ai/': 'improvement.md → ai/',
    'Runs on its own trigger: when the harness itself is wrong or stale.': '独自のきっかけで動く：ハーネス自体が誤っているか古いとき。',
    'Order shown is the normal composition; not every task runs all 13.': '図の順は通常の組み合わせ。すべての作業が 13 すべてを使うわけではない。',
    '07 · The skill shape': '07 · スキルの形',
    'Every SKILL.md has the same eight parts — on purpose': 'すべての SKILL.md は、意図して同じ 8 部構成を持つ',
    'Purpose · inputs & source order': '目的 · 入力と参照元の順序',
    'Bound what the skill needs before it starts.': '始める前に必要なものを限定する。',
    'Execution steps & applicable rules': '実行の手順と適用するルール',
    'Every step is tied to the rule that governs it — no implicit “current standard”.': '各ステップをそれを定めるルールに結び付け、暗黙の「現行基準」を残さない。',
    'Tools & environment': 'ツールと環境',
    'Honest about what can’t be done without a missing toolchain.': '欠けているツールがあると何ができないかを正直に示す。',
    'Outputs, templates, IDs, locations': '成果物、テンプレート、ID、保存場所',
    '`REQ` `BD` `DD` `DB` `SCR` `TC` `DEC` `WI` IDs and paths are explicit, not guesswork.': '`REQ` `BD` `DD` `DB` `SCR` `TC` `DEC` `WI` の ID と場所を推測に任せず明示する。',
    'Checklist · termination & failure': 'チェックリスト · 終了と失敗時',
    '“Done” becomes a checkable claim, not an assertion.': '「完了」を主張ではなく確認できるものにする。',
    'Work-item update & handover': '作業項目の更新と引き継ぎ',
    'Makes the pipeline resumable across agents and sessions.': 'エージェントやセッションをまたいで流れを再開できるようにする。',
    '08 · Rules': '08 · ルール',
    'Eight rule files: one current standard per area': '8 つのルールファイル：領域ごとに 1 つの現行基準',
    'Skills cite these instead of restating them, so the same change always meets the same bar.': 'スキルは基準を書き直さずにこれを参照するため、同じ変更は常に同じ基準を満たす。',
    'Preserve approved scope · stable IDs, link don’t duplicate · record unresolved decisions · focused changes': '承認された範囲を守る · 安定した ID、複製せずリンク · 未解決の判断を記録 · 焦点を絞った変更',
    'English source · EN + JA PDF of every doc · Japanese UI text quoted with an English gloss · number-first IDs, one folder per number': '英語が原本 · 全文書の英日 PDF · 日本語 UI の引用に英語の対訳 · 番号を先頭にした ID、番号ごとに 1 フォルダ',
    'Vite + TypeScript, strict (no `any`) · WCAG 2.2 AA · config via import.meta.env, no secrets in the browser': 'Vite + TypeScript、厳格（`any` なし）· WCAG 2.2 AA · 設定は import.meta.env、ブラウザに秘密情報を置かない',
    '.NET 10 · nullable types · RFC 9457 errors, no leaked detail · structured logs · OpenTelemetry on new endpoints': '.NET 10 · nullable 型 · RFC 9457 のエラー、詳細を漏らさない · 構造化ログ · 新しいエンドポイントに OpenTelemetry',
    'PostgreSQL · parameterized SQL only · expand/contract on live tables · least-privilege app role · recovery limits first': 'PostgreSQL · パラメーター化 SQL のみ · 使用中のテーブルは expand/contract · 最小権限のアプリロール · 先に復旧の限界',
    'Trace to acceptance criteria · pyramid shape · resettable data · quarantine flaky tests · not run ≠ pass': '受け入れ基準に結び付ける · ピラミッド型 · リセットできるデータ · 不安定なテストは隔離 · 未実行 ≠ 合格',
    'Branch + worktree per work item · small focused PRs · no direct push · squash-merge · review ≠ merge': '作業項目ごとにブランチと worktree · 小さく焦点を絞った PR · 直接 push しない · squash マージ · レビュー ≠ マージ',
    'SHA-pinned actions · read-only default permissions · OIDC over long-lived secrets · non-root scanned images': 'SHA 固定のアクション · 既定の権限は読み取り専用 · 長期の秘密情報より OIDC · 非 root のスキャン済みイメージ',
    '09 · Checklists': '09 · チェックリスト',
    'Four gates, each at the moment it matters': '4 つの関門、それぞれ必要な瞬間に',
    'Point-in-time pass/fail checks — “did this follow the rules” stops being something held in memory.': 'その時点での合否の確認 — 「ルールに従ったか」を記憶に頼らない。',
    'before dependent implementation': '依存する実装の前',
    'Stable IDs + acceptance criteria': '安定した ID と受け入れ基準',
    'DD agrees with BD; API/DB agree': 'DD が BD と一致、API と DB が一致',
    'Decisions resolved; tests map to design': '判断を解決済み、テストが設計に対応',
    'Security/PII, WCAG, migration, tracing specified': 'セキュリティ・個人情報、WCAG、マイグレーション、トレースを規定',
    'before merging a security-relevant change': 'セキュリティに関わる変更のマージ前',
    'Auth/authz on every changed endpoint': '変更したすべてのエンドポイントに認証・認可',
    'Input validated; no concatenated queries': '入力を検証、連結したクエリなし',
    'No secrets; vetted dependencies': '秘密情報なし、審査済みの依存関係',
    'No leaky errors; least privilege; threat model': '情報を漏らすエラーなし、最小権限、脅威モデル',
    'before reporting completion': '完了を報告する前',
    'Scope and plan revision identifiable': '範囲と計画のリビジョンが特定できる',
    'Checks recorded; not-run has a reason': '確認を記録、未実行には理由',
    'Stayed within authorization': '権限の範囲内にとどまった',
    'Another agent can continue from the files': '別のエージェントがファイルから続けられる',
    'before an authorized deployment': '承認されたデプロイの前',
    'Target config and migration plan confirmed': '対象の設定とマイグレーション計画を確認',
    'Rollback executable, not just described': 'ロールバックが記述だけでなく実行できる',
    'Smoke criteria and monitoring defined': 'スモークテストの基準と監視を定義',
    'Image/version traceable to its PR': 'イメージ・バージョンを PR までたどれる',
    '10 · Templates': '10 · テンプレート',
    'Every output starts from a real, named document format': 'すべての成果物は、実在する名前のある文書形式から始まる',
    'Chosen to match the artifact’s purpose — so the output is useful, not a formality.': '成果物の目的に合わせて選び、形だけでなく役立つものにする。',
    'TEMPLATE': 'テンプレート',
    'MODELED ON': '倣う形式',
    'CAPTURES': '記録するもの',
    'PRD conventions': 'PRD の慣習',
    'REQ-### with success + failure criteria, “not doing”': '成功・失敗の基準付きの REQ-###、「行わないこと」',
    'PMI-style implementation plan': 'PMI 式の実装計画',
    'Steps with verification, authorized actions, revisions kept': '検証付きのステップ、承認された操作、リビジョンを保持',
    'RAG status report': 'RAG 状況報告',
    'State, accomplishments, risks, single next action': '状態、成果、リスク、1 つの次の行動',
    'Decision log': '意思決定記録',
    'Context, options, answer, rationale, impact': '背景、選択肢、答え、理由、影響',
    'Traceability matrix + test log': 'トレーサビリティマトリクス + テスト記録',
    'REQ → design → code → test; real results': 'REQ → 設計 → コード → テスト、実際の結果',
    'MADR': 'MADR',
    'Drivers, options, outcome, consequences': '要因、選択肢、結果、帰結',
    '基本設計書': '基本設計書',
    'Flows, screens, Mermaid diagrams, SVG wireframes': '業務の流れ、画面、Mermaid の図、SVG ワイヤーフレーム',
    '詳細設計書 family': '詳細設計書 一式',
    'Main DD + API · function · screen-processing': 'メインの DD + API · 機能 · 画面処理',
    'テーブル定義書 + ER': 'テーブル定義書 + ER',
    'Tables, indexes, constraints, migration limits': 'テーブル、インデックス、制約、マイグレーションの限界',
    'IEEE 829-1998': 'IEEE 829-1998',
    'Items, approach, cases, results, gaps': '対象、方針、ケース、結果、不足',
    'Google code-review categories': 'Google のコードレビューの観点',
    'Design, functionality, complexity, tests …': '設計、機能、複雑さ、テスト …',
    'Rust-style RFC': 'Rust 式の RFC',
    'Motivation, alternatives, evaluation, adoption': '動機、代替案、評価、採用',
    '11 · Durable state': '11 · 永続的な状態',
    'The work item is the memory — not the chat': '記憶はチャットではなく作業項目にある',
    'Switching from Claude to Codex mid-task means reading the work item and continuing, not restarting.': '作業の途中で Claude から Codex に替わっても、やり直さずに作業項目を読んで続ける。',
    'What and why: REQ-### and acceptance criteria': '何を、なぜ：REQ-### と受け入れ基準',
    'Every revision shown and approved before its work; all kept, oldest first': '各リビジョンは作業前に示して承認を得る。すべて古い順に保持',
    'Current state, risks, the single next action': '現在の状態、リスク、1 つの次の行動',
    'Every question that stopped an agent, and its answer': 'エージェントを止めたすべての問いとその答え',
    'What makes “done” checkable after the fact': '「完了」を後から確認できるようにするもの',
    '+ design docs under `docs/en/…` (BD, DB, DD, ADR, tests), each with EN and JA PDFs': '+ `docs/en/…` の設計文書（BD、DB、DD、ADR、テスト）。それぞれ英日の PDF 付き',
    'status.md states': 'status.md の状態',
    'Any active state can become **blocked** — recorded with its owner and impact.': '作業中の状態はどれも **blocked** になりうる — 担当者と影響を記録する。',
    '12 · Design principles': '12 · 設計原則',
    'Five principles behind every file': 'すべてのファイルの背後にある 5 つの原則',
    'One shared, agent-neutral source': 'エージェントに依存しない、共有の 1 つの原本',
    'Process lives only in ai/. Adapters (AGENTS.md, CLAUDE.md, .claude/, a .codex/ if ever needed) route to it and never duplicate it — agent-specific tooling stays out of shared skills.': '手順は ai/ だけに置く。接続部分（AGENTS.md、CLAUDE.md、.claude/、必要になれば .codex/）はそこに振り分けるだけで、複製しない — エージェント固有のツールは共有のスキルに入れない。',
    'Markdown is the contract, not the executor': 'Markdown は契約であり、実行者ではない',
    'The harness defines what correct and done mean. Scripts, test runners and GitHub Actions do the work — and their real output is recorded, not assumed.': 'ハーネスは正しさと完了の意味を定める。作業はスクリプト、テストランナー、GitHub Actions が行い、その実際の出力を仮定ではなく記録する。',
    'An approved plan is the scope of authority': '承認された計画が権限の範囲',
    'Steps don’t need re-approval, but the plan’s scope and the pause conditions are hard limits. Content an agent merely read is never authorization.': 'ステップごとの再承認は不要だが、計画の範囲と一時停止の条件は厳格な限界。エージェントが単に読んだ内容は権限にならない。',
    'A conclusion requires evidence': '結論には証跡が必要',
    '“Done”, “passing”, “deployed” are claimed only after a recorded, actually-run check. Not run is recorded as not run.': '「完了」「合格」「デプロイ済み」は、記録された実際に実行した確認の後にだけ主張する。未実行は未実行として記録する。',
    'The harness improves itself, on the record': 'ハーネスは記録に残る形で自らを改善する',
    'Gaps are fixed through the harness-improvement skill and evaluation cases — never as a silent edit to shared guidance.': '不足は harness-improvement スキルと評価ケースで直す — 共有の指針を黙って書き換えない。',
    '13 · Where this stands': '13 · 現状',
    'Four runs of the chain — Screens A, B and C are done': '一連の流れを 4 回実行 — Screen A、B、C は完了',
    'WI-001 – WI-004 · WHAT EACH RUN EXERCISED': 'WI-001 〜 WI-004 · それぞれの実行で確かめたこと',
    'WI-001': 'WI-001',
    'project-bootstrap: skeleton, auth foundation, local Compose environment, CI': 'project-bootstrap：骨組み、認証の基盤、ローカルの Compose 環境、CI',
    'WI-002 · Screen A': 'WI-002 · Screen A',
    'The first end-to-end feature: requirements → plan → BD → DB → four DD documents + mockup → code → unit, integration and E2E tests with axe → checklists → PR': '最初のエンドツーエンドの機能：要件 → 計画 → BD → DB → 4 つの DD 文書 + モックアップ → コード → axe を含む単体・結合・E2E テスト → チェックリスト → PR',
    'WI-003 · Screen B': 'WI-003 · Screen B',
    'Building on an existing screen: evolving a live schema, reusing shared modules and endpoints, amending Screen A’s design': '既存の画面の上に作る：稼働中のスキーマの変更、共通のモジュールとエンドポイントの再利用、Screen A の設計の修正',
    'WI-004 · Screen C': 'WI-004 · Screen C',
    'A read-only dashboard over one consistent snapshot, a design revised after mockup review, and a navbar on every screen': '1 つの一貫したスナップショットに基づく読み取り専用のダッシュボード、モックアップレビュー後の設計の修正、全画面のナビゲーションバー',
    'Each run is recorded in `work-items/WI-00N/`.': '各実行は `work-items/WI-00N/` に記録されている。',
    'Where it stands': '現在の状況',
    'CI runs green': 'CI は合格',
    'Backend, frontend and E2E (Compose + Playwright) on every pull request to master; documentation-only changes skip it.': 'master へのすべてのプルリクエストでバックエンド、フロントエンド、E2E（Compose + Playwright）を実行。文書だけの変更では実行しない。',
    'Gaps fixed on the record': '不足は記録に残る形で修正',
    'What the chain exposed was fixed through harness-improvement, not by silent edits to shared guidance.': '流れの中で見つかった不足は、共有の指針を黙って書き換えず、harness-improvement で直した。',
    'Open project decisions': 'プロジェクトの未決事項',
    'Deployment host, merge/deploy permissions, demo videos, the full role matrix — the owner’s to make.': 'デプロイ先、マージ・デプロイ権限、デモ動画、完全なロール設計 — 決めるのはオーナー。',
    'NEXT': '次',
    'The locked roadmap is complete and no next work item is planned. The untested part of the harness is deployment: release-readiness and the ci-cd skill’s deployment half wait on a deployment target.': '固定したロードマップは完了し、次の作業項目は計画されていない。ハーネスで未検証なのはデプロイで、release-readiness と ci-cd スキルのデプロイの部分はデプロイ先の決定を待っている。',
}
