// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductionManagementAI.Infrastructure;

#nullable disable

namespace ProductionManagementAI.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("ProductionManagementAI.Domain.PlantCalendar.CalendarState", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<DateOnly>("ActivatedOn")
                        .HasColumnType("date")
                        .HasColumnName("activated_on");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("revision");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_plant_calendar_state");

                    b.ToTable("plant_calendar_state", null, t =>
                        {
                            t.HasCheckConstraint("ck_calendar_state_date", "activated_on BETWEEN DATE '0001-01-01' AND DATE '9999-12-31'");

                            t.HasCheckConstraint("ck_calendar_state_revision", "revision >= 1");

                            t.HasCheckConstraint("ck_calendar_state_singleton", "id = 1");

                            t.HasCheckConstraint("ck_calendar_state_zone", "time_zone_id = btrim(time_zone_id) AND length(time_zone_id) > 0");
                        });
                });

            modelBuilder.Entity("ProductionManagementAI.Domain.PlantCalendar.ExceptionRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly>("CalendarDate")
                        .HasColumnType("date")
                        .HasColumnName("calendar_date");

                    b.Property<short>("CalendarId")
                        .HasColumnType("smallint")
                        .HasColumnName("calendar_id");

                    b.Property<long>("CommitRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("commit_revision");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_current");

                    b.Property<bool>("IsRemoved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_removed");

                    b.Property<bool?>("IsWorking")
                        .HasColumnType("boolean")
                        .HasColumnName("is_working");

                    b.Property<Guid?>("LineId")
                        .HasColumnType("uuid")
                        .HasColumnName("line_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<decimal?>("WorkingHours")
                        .HasColumnType("numeric")
                        .HasColumnName("working_hours");

                    b.HasKey("Id")
                        .HasName("pk_calendar_exception_revisions");

                    b.HasIndex("LineId")
                        .HasDatabaseName("ix_calendar_exception_line")
                        .HasFilter("line_id IS NOT NULL");

                    b.HasIndex("CalendarId", "CommitRevision")
                        .IsUnique()
                        .HasDatabaseName("ux_calendar_exception_commit");

                    b.HasIndex("CalendarId", "LineId", "CalendarDate")
                        .IsUnique()
                        .HasDatabaseName("ux_calendar_exception_current")
                        .HasFilter("is_current");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("CalendarId", "LineId", "CalendarDate"), false);

                    b.ToTable("plant_calendar_exception_revisions", null, t =>
                        {
                            t.HasCheckConstraint("ck_calendar_exception_date", "calendar_date BETWEEN DATE '0001-01-01' AND DATE '9999-12-31'");

                            t.HasCheckConstraint("ck_calendar_exception_hours", "working_hours IS NULL OR (working_hours > 0 AND working_hours <= 24 AND scale(working_hours) <= 3)");

                            t.HasCheckConstraint("ck_calendar_exception_payload", "(is_removed AND is_working IS NULL AND working_hours IS NULL AND reason IS NULL) OR (NOT is_removed AND is_working IS NOT NULL AND (is_working OR working_hours IS NULL))");

                            t.HasCheckConstraint("ck_calendar_exception_revision", "commit_revision >= 1");
                        });
                });

            modelBuilder.Entity("ProductionManagementAI.Domain.PlantCalendar.WeeklyRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<short>("CalendarId")
                        .HasColumnType("smallint")
                        .HasColumnName("calendar_id");

                    b.Property<long>("CommitRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("commit_revision");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_current");

                    b.Property<bool>("IsWithdrawn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_withdrawn");

                    b.Property<short?>("WorkingWeekdays")
                        .HasColumnType("smallint")
                        .HasColumnName("working_weekdays");

                    b.HasKey("Id")
                        .HasName("pk_calendar_weekly_revisions");

                    b.HasIndex("CalendarId", "CommitRevision")
                        .IsUnique()
                        .HasDatabaseName("ux_calendar_weekly_commit");

                    b.HasIndex("CalendarId", "EffectiveFrom")
                        .IsUnique()
                        .IsDescending(false, true)
                        .HasDatabaseName("ux_calendar_weekly_current")
                        .HasFilter("is_current");

                    b.ToTable("plant_calendar_weekly_revisions", null, t =>
                        {
                            t.HasCheckConstraint("ck_calendar_weekly_date", "effective_from BETWEEN DATE '0001-01-01' AND DATE '9999-12-31'");

                            t.HasCheckConstraint("ck_calendar_weekly_payload", "(is_withdrawn AND working_weekdays IS NULL) OR (NOT is_withdrawn AND working_weekdays IS NOT NULL AND working_weekdays BETWEEN 0 AND 127)");

                            t.HasCheckConstraint("ck_calendar_weekly_revision", "commit_revision >= 1");
                        });
                });

            modelBuilder.Entity("ProductionManagementAI.Domain.ProductionLines.ProductionLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("WorkingHoursPerDay")
                        .HasColumnType("numeric")
                        .HasColumnName("working_hours_per_day");

                    b.HasKey("Id")
                        .HasName("pk_production_lines");

                    b.ToTable("production_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_production_lines_code_trimmed", "code = btrim(code) AND length(code) > 0");

                            t.HasCheckConstraint("ck_production_lines_hours_range", "working_hours_per_day > 0 AND working_hours_per_day <= 24");

                            t.HasCheckConstraint("ck_production_lines_hours_scale", "scale(working_hours_per_day) <= 3");

                            t.HasCheckConstraint("ck_production_lines_name_trimmed", "name = btrim(name) AND length(name) > 0");
                        });
                });

            modelBuilder.Entity("ProductionManagementAI.Domain.ProductionLines.ProductionLineProduct", b =>
                {
                    b.Property<Guid>("LineId")
                        .HasColumnType("uuid")
                        .HasColumnName("line_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ConfirmedUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("confirmed_unit");

                    b.Property<long>("ConfirmedUnitRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("confirmed_unit_revision");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal>("MinutesPerUnit")
                        .HasColumnType("numeric")
                        .HasColumnName("minutes_per_unit");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("now()");

                    b.HasKey("LineId", "ProductId")
                        .HasName("pk_production_line_products");

                    b.HasIndex("ProductId", "LineId")
                        .HasDatabaseName("ix_line_products_product_line");

                    b.ToTable("production_line_products", null, t =>
                        {
                            t.HasCheckConstraint("ck_line_products_confirmed_revision", "confirmed_unit_revision >= 0");

                            t.HasCheckConstraint("ck_line_products_confirmed_unit", "confirmed_unit IN ('個','本','枚','台','セット','kg','m')");

                            t.HasCheckConstraint("ck_line_products_minutes_range", "minutes_per_unit > 0 AND minutes_per_unit <= 999999999.999");

                            t.HasCheckConstraint("ck_line_products_minutes_scale", "scale(minutes_per_unit) <= 3");
                        });
                });

            modelBuilder.Entity("ProductionManagementAI.Domain.ProductionOrders.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DrawingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("drawing_number");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.Property<long>("UnitRevision")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("unit_revision");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_products_sku");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_name_not_blank", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_products_sku_trimmed", "sku = btrim(sku) AND length(sku) > 0");

                            t.HasCheckConstraint("ck_products_unit", "unit IN ('個', '本', '枚', '台', 'セット', 'kg', 'm')");

                            t.HasCheckConstraint("ck_products_unit_revision", "unit_revision >= 0");
                        });
                });

            modelBuilder.Entity("ProductionManagementAI.Domain.ProductionOrders.ProductionOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid?>("LineId")
                        .HasColumnType("uuid")
                        .HasColumnName("line_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("order_number")
                        .HasComputedColumnSql("'PO-' || order_year::text || '-' || lpad(order_seq::text, 5, '0')", true);

                    b.Property<int>("OrderSeq")
                        .HasColumnType("integer")
                        .HasColumnName("order_seq");

                    b.Property<short>("OrderYear")
                        .HasColumnType("smallint")
                        .HasColumnName("order_year");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_production_orders");

                    b.HasIndex("OrderNumber")
                        .HasDatabaseName("ix_production_orders_order_number_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("OrderNumber"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("OrderNumber"), new[] { "gin_trgm_ops" });

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_production_orders_product_id");

                    b.HasIndex("DueDate", "OrderNumber")
                        .HasDatabaseName("ix_production_orders_due_date_order_number");

                    b.HasIndex("LineId", "ProductId")
                        .HasDatabaseName("ix_orders_line_product")
                        .HasFilter("line_id IS NOT NULL");

                    b.HasIndex("OrderYear", "OrderSeq")
                        .IsUnique()
                        .HasDatabaseName("ix_production_orders_order_year_order_seq");

                    b.HasIndex(new[] { "DueDate", "OrderNumber" }, "ix_production_orders_active_due_date")
                        .HasDatabaseName("ix_production_orders_active_due_date")
                        .HasFilter("status IN ('Draft', 'InProgress')");

                    b.HasIndex(new[] { "CompletedAtUtc" }, "ix_production_orders_completed_at_utc")
                        .HasDatabaseName("ix_production_orders_completed_at_utc")
                        .HasFilter("completed_at_utc IS NOT NULL");

                    b.ToTable("production_orders", null, t =>
                        {
                            t.HasCheckConstraint("ck_production_orders_completed_at_matches_status", "(status = 'Completed') = (completed_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_production_orders_completed_at_not_before_created", "completed_at_utc IS NULL OR completed_at_utc >= created_at_utc");

                            t.HasCheckConstraint("ck_production_orders_order_seq_range", "order_seq BETWEEN 1 AND 99999");

                            t.HasCheckConstraint("ck_production_orders_order_year_range", "order_year BETWEEN 2000 AND 9999");

                            t.HasCheckConstraint("ck_production_orders_quantity_max", "quantity <= 999999999");

                            t.HasCheckConstraint("ck_production_orders_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("ck_production_orders_quantity_scale", "scale(quantity) <= 3");

                            t.HasCheckConstraint("ck_production_orders_status", "status IN ('Draft', 'InProgress', 'Completed', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("ProductionManagementAI.Infrastructure.Identity.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_normalized_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("ProductionManagementAI.Infrastructure.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("ix_users_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_user_name");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ProductionManagementAI.Infrastructure.ProductionOrders.ProductionOrderNumberCounter", b =>
                {
                    b.Property<short>("OrderYear")
                        .HasColumnType("smallint")
                        .HasColumnName("order_year");

                    b.Property<int>("LastSeq")
                        .HasColumnType("integer")
                        .HasColumnName("last_seq");

                    b.HasKey("OrderYear")
                        .HasName("pk_production_order_number_counters");

                    b.ToTable("production_order_number_counters", null, t =>
                        {
                            t.HasCheckConstraint("ck_production_order_number_counters_last_seq_range", "last_seq BETWEEN 1 AND 99999");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("ProductionManagementAI.Infrastructure.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ProductionManagementAI.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ProductionManagementAI.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("ProductionManagementAI.Infrastructure.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("ProductionManagementAI.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ProductionManagementAI.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });

            modelBuilder.Entity("ProductionManagementAI.Domain.PlantCalendar.ExceptionRevision", b =>
                {
                    b.HasOne("ProductionManagementAI.Domain.PlantCalendar.CalendarState", null)
                        .WithMany()
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_exception_state");

                    b.HasOne("ProductionManagementAI.Domain.ProductionLines.ProductionLine", null)
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_calendar_exception_line");
                });

            modelBuilder.Entity("ProductionManagementAI.Domain.PlantCalendar.WeeklyRevision", b =>
                {
                    b.HasOne("ProductionManagementAI.Domain.PlantCalendar.CalendarState", null)
                        .WithMany()
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_weekly_state");
                });

            modelBuilder.Entity("ProductionManagementAI.Domain.ProductionLines.ProductionLineProduct", b =>
                {
                    b.HasOne("ProductionManagementAI.Domain.ProductionLines.ProductionLine", null)
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_line_products_line");

                    b.HasOne("ProductionManagementAI.Domain.ProductionOrders.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_line_products_product");
                });

            modelBuilder.Entity("ProductionManagementAI.Domain.ProductionOrders.ProductionOrder", b =>
                {
                    b.HasOne("ProductionManagementAI.Domain.ProductionOrders.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_production_orders_products_product_id");

                    b.HasOne("ProductionManagementAI.Domain.ProductionLines.ProductionLineProduct", null)
                        .WithMany()
                        .HasForeignKey("LineId", "ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_orders_line_product");
                });
#pragma warning restore 612, 618
        }
    }
}
