using System.Text;

namespace ProductionManagementAI.Domain.ProductionOrders;

/// <summary>
/// One production order (DD-001 module 1). Owns every invariant that needs no I/O: status transitions,
/// the product/quantity lock, and quantity/notes value rules. Date rules need the plant clock and live in
/// the Application service (DD-001-FN).
/// </summary>
public sealed class ProductionOrder
{
    public const int MaxQuantity = 999_999_999; // DEC-024
    public const int MaxNotesLength = 500; // REQ-016, counted in Unicode code points

    private ProductionOrder()
    {
    }

    public Guid Id { get; private set; }
    public short OrderYear { get; private set; }
    public int OrderSeq { get; private set; }

    /// <summary>Generated by PostgreSQL from <see cref="OrderYear"/> and <see cref="OrderSeq"/> (DB-002, DEC-012).</summary>
    public string OrderNumber { get; private set; } = string.Empty;

    public Guid ProductId { get; private set; }
    public int Quantity { get; private set; }
    public DateOnly DueDate { get; private set; }
    public ProductionOrderStatus Status { get; private set; }
    public string? Notes { get; private set; }
    public DateTimeOffset CreatedAtUtc { get; private set; }
    public DateTimeOffset UpdatedAtUtc { get; private set; }

    /// <summary>
    /// When the order became <c>Completed</c> (WI-004 REQ-033, DB-004). Set only by <see cref="Update"/> on the
    /// <c>InProgress → Completed</c> transition; <c>Completed</c> is terminal, so it never changes afterwards.
    /// </summary>
    public DateTimeOffset? CompletedAtUtc { get; private set; }

    /// <summary>PostgreSQL <c>xmin</c>, the optimistic-concurrency token (DEC-014).</summary>
    public uint RowVersion { get; private set; }

    public bool IsProductQuantityEditable => Status == ProductionOrderStatus.Draft;

    public static ProductionOrder Create(
        Guid productId, int quantity, DateOnly dueDate, string? notes, short orderYear, int orderSeq, DateTimeOffset utcNow)
    {
        ThrowIfInvalid(quantity, notes);

        return new ProductionOrder
        {
            Id = Guid.CreateVersion7(utcNow),
            OrderYear = orderYear,
            OrderSeq = orderSeq,
            ProductId = productId,
            Quantity = quantity,
            DueDate = dueDate,
            Status = ProductionOrderStatus.Draft,
            Notes = NormalizeNotes(notes),
            CreatedAtUtc = utcNow,
            UpdatedAtUtc = utcNow,
        };
    }

    /// <summary>
    /// Applies an edit. Checks the lock (MSG-E008) before the transition (MSG-E007), and changes nothing
    /// when either fails, so a rejected request never partially applies (DEC-007).
    /// </summary>
    public void Update(
        Guid productId, int quantity, DateOnly dueDate, string? notes, ProductionOrderStatus status, DateTimeOffset utcNow)
    {
        ThrowIfInvalid(quantity, notes);

        if (!IsProductQuantityEditable && (productId != ProductId || quantity != Quantity))
        {
            throw new DomainRuleViolation(ProductionOrderMessages.LockedFieldChanged);
        }

        if (!Status.CanTransitionTo(status))
        {
            throw new DomainRuleViolation(ProductionOrderMessages.StatusTransitionNotAllowed);
        }

        var fromStatus = Status;
        ProductId = productId;
        Quantity = quantity;
        DueDate = dueDate;
        Notes = NormalizeNotes(notes);
        Status = status;
        UpdatedAtUtc = utcNow;

        // DD-001 v4 module 1 step 5: the save's own time, in the same save as the status change.
        if (fromStatus == ProductionOrderStatus.InProgress && status == ProductionOrderStatus.Completed)
        {
            CompletedAtUtc = utcNow;
        }
    }

    /// <returns>A message ID, or <c>null</c> when valid (V-02).</returns>
    public static string? ValidateQuantity(int quantity) => quantity switch
    {
        < 1 => ProductionOrderMessages.QuantityInvalid,
        > MaxQuantity => ProductionOrderMessages.QuantityTooLarge,
        _ => null,
    };

    /// <returns>A message ID, or <c>null</c> when valid (V-05). Counts code points, matching PostgreSQL varchar(500).</returns>
    public static string? ValidateNotes(string? notes)
    {
        var normalized = NormalizeNotes(notes);
        return normalized is not null && CountCodePoints(normalized) > MaxNotesLength
            ? ProductionOrderMessages.NotesTooLong
            : null;
    }

    /// <summary>Trims; empty or whitespace-only becomes <c>null</c> (REQ-016).</summary>
    public static string? NormalizeNotes(string? notes)
    {
        var trimmed = notes?.Trim();
        return string.IsNullOrEmpty(trimmed) ? null : trimmed;
    }

    private static int CountCodePoints(string value)
    {
        var count = 0;
        foreach (Rune _ in value.EnumerateRunes())
        {
            count++;
        }

        return count;
    }

    private static void ThrowIfInvalid(int quantity, string? notes)
    {
        // The service validates first and reports field errors; reaching here with bad values is a programming error.
        if (ValidateQuantity(quantity) is not null || ValidateNotes(notes) is not null)
        {
            throw new ArgumentException("Production order values must be validated before calling the domain model.");
        }
    }
}
