import { test,expect } from '@playwright/test'
import { signIn,expectNoAxeViolations,futureDate } from './helpers'
test.beforeEach(async({page})=>{await signIn(page)})
test('TC-402/403/405: dated closure, retained removal and centered confirmation',async({page})=>{
 const date=futureDate(15),reason=`試験停止（手動設定）-${Date.now()}`
 await page.goto(`/plant-calendar?month=${date.slice(0,7)}&date=${date}&mode=month`)
 await expect(page.getByRole('heading',{level:1,name:'稼働カレンダー'})).toBeVisible()
 await expect(page.getByRole('table')).toBeVisible()
 await expect(page.getByRole('button',{name:'日付例外',exact:true})).toBeVisible()
 await expectNoAxeViolations(page)
 await page.getByRole('button',{name:'日付例外',exact:true}).click()
 await page.getByRole('radio',{name:'非稼働日',exact:true}).check()
 await page.getByLabel('理由',{exact:true}).fill(reason)
 await expectNoAxeViolations(page)
 await page.getByRole('button',{name:'保存',exact:true}).click()
 await expect(page.getByText('保存しました。',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'日付例外',exact:true}).click()
 await expect(page.getByRole('radio',{name:'非稼働日',exact:true})).toBeChecked()
 await page.getByRole('button',{name:'例外を削除',exact:true}).click()
 const dialog=page.getByRole('dialog');await expect(dialog).toBeVisible()
 await expect(dialog.getByRole('button',{name:'キャンセル',exact:true})).toBeFocused()
 const bounds=await dialog.evaluate(e=>{const r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2,vw:innerWidth,vh:innerHeight}})
 expect(Math.abs(bounds.x-bounds.vw/2)).toBeLessThanOrEqual(2)
 expect(Math.abs(bounds.y-bounds.vh/2)).toBeLessThanOrEqual(2)
 await expectNoAxeViolations(page)
 await page.keyboard.press('Escape');await expect(dialog).toBeHidden()
 await page.getByRole('button',{name:'例外を削除',exact:true}).click()
 await dialog.getByRole('button',{name:'例外を削除',exact:true}).click()
 await expect(page.getByText('保存しました。',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'履歴',exact:true}).click()
 await expect(page.getByText('削除・取消の記録',{exact:true}).first()).toBeVisible()
 await expect(page.getByText(reason,{exact:true})).toBeVisible()
})
test('TC-402/405: all-closed weekly definition, draft departure and withdrawal',async({page})=>{
 const date=futureDate(16)
 await page.goto(`/plant-calendar?month=${date.slice(0,7)}&date=${date}&mode=weekly`)
 await expect(page.getByRole('heading',{name:`編集: ${date}`,exact:true})).toBeVisible()
 for(const name of ['月','火','水','木','金','土','日'])await page.getByRole('checkbox',{name,exact:true}).uncheck()
 await page.getByRole('link',{name:'製品マスタ',exact:true}).click()
 await expect(page.getByRole('dialog')).toBeVisible()
 await page.getByRole('dialog').getByRole('button',{name:'キャンセル',exact:true}).click()
 await expect(page).toHaveURL(/plant-calendar/)
 await page.getByRole('button',{name:'保存',exact:true}).click()
 await expect(page.getByText('保存しました。',{exact:true})).toBeVisible()
 await page.goto(`/plant-calendar?month=${date.slice(0,7)}&date=${date}&mode=weekly`)
 await page.getByRole('button',{name:'予約を取消',exact:true}).click()
 await page.getByRole('dialog').getByRole('button',{name:'予約を取消',exact:true}).click()
 await expect(page.getByText('保存しました。',{exact:true})).toBeVisible()
})

test('TC-403/405: committed response loss remains Unknown without replay',async({page})=>{
 const date=futureDate(19),reason=`結果確認-${Date.now()}`
 await page.goto(`/plant-calendar?month=${date.slice(0,7)}&date=${date}&mode=day`)
 await page.getByRole('radio',{name:'非稼働日',exact:true}).check()
 await page.getByLabel('理由',{exact:true}).fill(reason)
 const before=await (await page.request.get(`/api/plant-calendar/exception-history?date=${date}`)).json()
 let writes=0
 await page.route('**/api/plant-calendar/exceptions',async route=>{writes++;await route.fetch();await route.abort('failed')})
 await page.getByRole('button',{name:'保存',exact:true}).click()
 await expect(page.getByText('保存結果を確認できません。再送せず現在の状態を確認してください。',{exact:true})).toBeVisible()
 await expect(page.getByRole('button',{name:'保存',exact:true})).toBeDisabled()
 await expect(page.getByLabel('理由',{exact:true})).toHaveValue(reason)
 await page.unroute('**/api/plant-calendar/exceptions')
 await page.getByRole('button',{name:'現在の状態を確認',exact:true}).click()
 await expect(page.getByRole('button',{name:'入力を破棄して現在の状態を使用',exact:true})).toBeEnabled()
 await expect(page.getByText('現在の参照結果です。先ほどの保存成功を証明するものではありません。',{exact:true}).first()).toBeVisible()
 const after=await (await page.request.get(`/api/plant-calendar/exception-history?date=${date}`)).json()
 expect(after.totalCount).toBe(before.totalCount+1);expect(writes).toBe(1)
 await page.getByRole('button',{name:'入力を破棄して現在の状態を使用',exact:true}).click()
 await page.getByRole('dialog').getByRole('button',{name:'破棄',exact:true}).click()
 await expect(page.getByLabel('理由',{exact:true})).toHaveValue(reason)
 await expect(page.getByRole('button',{name:'保存',exact:true})).toBeDisabled()
})

test('TC-404: exact current kg capacity and invalid closed pair remain distinct',async({page})=>{
 const suffix=Date.now(),date=futureDate(21)
 const created=await page.request.post('/api/product-master',{data:{sku:`CAL-KG-${suffix}`,name:'能力試験製品',unit:'kg'}});expect(created.ok()).toBe(true)
 const product=await created.json()
 const eligibility=await (await page.request.get(`/api/production-lines/eligible?productId=${product.id}`)).json()
 const lineResponse=await page.request.post('/api/production-lines',{data:{code:`CAL-LINE-${suffix}`,name:'能力試験ライン',workingHoursPerDay:'8',products:[{productId:product.id,minutesPerUnit:'0.125',expectedUnit:'kg',expectedUnitRevision:eligibility.product.unitRevision,confirmUnit:true}]}});expect(lineResponse.ok()).toBe(true)
 const line=await lineResponse.json()
 const context=await (await page.request.get(`/api/plant-calendar/day?date=${date}&lineId=${line.id}`)).json()
 const saved=await page.request.put('/api/plant-calendar/exceptions',{data:{version:context.context.version,targetRevisionId:context.exception?.id??null,lineId:line.id,date,isWorking:true,workingHours:'4',reason:null}});expect(saved.ok()).toBe(true)
 await page.goto(`/plant-calendar?month=${date.slice(0,7)}&date=${date}&lineId=${line.id}&productId=${product.id}&mode=month`)
 await page.getByRole('button',{name:'能力を表示',exact:true}).click()
 await expect(page.getByText('1,920 kg',{exact:true})).toBeVisible()
 await expectNoAxeViolations(page)
 const day=await (await page.request.get(`/api/plant-calendar/day?date=${date}&lineId=${line.id}`)).json()
 const closed=await page.request.put('/api/plant-calendar/exceptions',{data:{version:day.context.version,targetRevisionId:day.exception.id,lineId:line.id,date,isWorking:false,workingHours:null,reason:null}});expect(closed.ok()).toBe(true)
 const retire=await page.request.post(`/api/product-master/${product.id}/retire`,{data:{version:product.version}});expect(retire.ok()).toBe(true)
 await page.getByRole('button',{name:'能力を表示',exact:true}).click()
 await expect(page.getByText('対象のライン・製品・組合せは停止中です。',{exact:true})).toBeVisible()
 await expect(page.getByText('1,920 kg',{exact:true})).toBeHidden()
})
test('TC-405: acknowledged success survives subsequent refresh failure',async({page})=>{
 const date=futureDate(22)
 await page.goto(`/plant-calendar?month=${date.slice(0,7)}&date=${date}&mode=day`)
 await page.getByRole('radio',{name:'非稼働日',exact:true}).check()
 await page.getByLabel('理由',{exact:true}).fill(`保存後確認-${Date.now()}`)
 await page.route('**/api/plant-calendar/line-choices?*',route=>route.fulfill({status:503,contentType:'application/problem+json',body:JSON.stringify({code:'CALENDAR_BUSY'})}))
 await page.getByRole('button',{name:'保存',exact:true}).click()
 await expect(page.getByText('保存しました。',{exact:true})).toBeVisible()
 await expect(page.getByText('保存は完了しましたが、表示の更新に失敗しました。',{exact:true})).toBeVisible()
 await expect(page.getByText('保存結果を確認できません。再送せず現在の状態を確認してください。',{exact:true})).toBeHidden()
 await page.unroute('**/api/plant-calendar/line-choices?*')
 await page.getByRole('button',{name:'再読込',exact:true}).click()
 await expect(page.getByText('保存しました。',{exact:true})).toBeVisible()
})
