import { test,expect } from '@playwright/test'
import { signIn,expectNoAxeViolations,futureDate } from './helpers'
test('TC-403/405/406: mobile agenda, keyboard dialog and reflow',async({page})=>{
 await signIn(page)
 const date=futureDate(18)
 await page.goto(`/plant-calendar?month=${date.slice(0,7)}&date=${date}&mode=month`)
 await expect(page.getByRole('heading',{level:1,name:'稼働カレンダー'})).toBeVisible()
 await expect(page.getByRole('table')).toBeHidden()
 const days=page.getByRole('button',{name:/^\d{4}-\d{2}-\d{2} /})
 await expect(days).toHaveCount(new Date(Number(date.slice(0,4)),Number(date.slice(5,7)),0).getDate())
 await page.getByRole('button',{name:'日付例外',exact:true}).click()
 await page.getByRole('combobox',{name:'日付例外',exact:true}).selectOption('yes')
 await page.getByRole('checkbox',{name:'ラインの現設定を使用',exact:true}).uncheck()
 await page.getByLabel('稼働時間（時間）',{exact:true}).fill('4.125')
 await page.getByLabel('理由',{exact:true}).fill('モバイル入力試験')
 await expectNoAxeViolations(page)
 await page.getByRole('button',{name:'キャンセル',exact:true}).click()
 const dialog=page.getByRole('dialog');await expect(dialog).toBeVisible()
 const position=await dialog.evaluate(e=>{const r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2,w:innerWidth,h:innerHeight}})
 expect(Math.abs(position.x-position.w/2)).toBeLessThanOrEqual(2)
 expect(Math.abs(position.y-position.h/2)).toBeLessThanOrEqual(2)
 await expect(dialog.getByRole('button',{name:'キャンセル',exact:true})).toBeFocused()
 await page.keyboard.press('Tab');await expect(dialog.getByRole('button',{name:'破棄',exact:true})).toBeFocused()
 await page.keyboard.press('Tab');await expect(dialog.getByRole('button',{name:'キャンセル',exact:true})).toBeFocused()
 await expectNoAxeViolations(page)
 await page.keyboard.press('Escape');await expect(dialog).toBeHidden()
 await expect(page.getByLabel('理由',{exact:true})).toHaveValue('モバイル入力試験')
 await page.getByRole('button',{name:'キャンセル',exact:true}).click()
 await dialog.getByRole('button',{name:'破棄',exact:true}).click()
 await expect(page).toHaveURL(/mode=month/)
 await page.setViewportSize({width:320,height:720})
 await expect(page.getByRole('heading',{level:1,name:'稼働カレンダー'})).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await expectNoAxeViolations(page)
})
