import { expect, test } from '@playwright/test'
import { expectNoAxeViolations, signIn } from './helpers'

test('TC-361/363: mobile cards and retirement dialog remain centered after scroll at 320/390px', async ({ page }) => {
  await signIn(page)
  const code = `MOBILE-${Date.now()}`
  const created = await page.request.post('/api/production-lines', { data: { code, name: 'モバイル試験ライン', workingHoursPerDay: '8', products: [] } })
  expect(created.status()).toBe(201)
  for (const width of [320, 390]) {
    await page.setViewportSize({ width, height: 844 })
    await page.goto(`/production-lines?q=${code}`)
    const retire = page.getByRole('button', { name: `${code}を使用停止`, exact: true })
    await expect(retire).toBeVisible()
    await page.evaluate(() => scrollTo(0, document.body.scrollHeight))
    await retire.click()
    const dialog = page.getByRole('dialog')
    const bounds = await dialog.evaluate(element => { const rect = element.getBoundingClientRect(); return { x: rect.x, y: rect.y, width: rect.width, height: rect.height, vw: innerWidth, vh: innerHeight } })
    expect(Math.abs(bounds.x + bounds.width / 2 - bounds.vw / 2)).toBeLessThanOrEqual(2)
    expect(Math.abs(bounds.y + bounds.height / 2 - bounds.vh / 2)).toBeLessThanOrEqual(2)
    expect(bounds.x).toBeGreaterThanOrEqual(15); expect(bounds.y).toBeGreaterThanOrEqual(15)
    await expect(dialog.getByRole('button', { name: 'キャンセル' })).toBeFocused()
    await expectNoAxeViolations(page)
    await page.keyboard.press('Escape')
    await expect(retire).toBeFocused()
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)
    expect(overflow).toBe(false)
  }
})

test('TC-363: narrow desktop header and 200-percent text zoom preserve controls and dialog access', async ({ page }) => {
  await signIn(page)
  const code = `ZOOM-${Date.now()}`
  await page.request.post('/api/production-lines', { data: { code, name: '拡大試験ライン', workingHoursPerDay: '8', products: [] } })
  await page.setViewportSize({ width: 640, height: 900 })
  await page.goto(`/production-lines?q=${code}`)
  await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false)
  await page.setViewportSize({ width: 1280, height: 900 })
  await page.evaluate(() => { document.documentElement.style.zoom = '2' })
  await page.getByRole('button', { name: `${code}を使用停止`, exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('button', { name: 'キャンセル' })).toBeVisible()
  await expect(dialog.getByRole('button', { name: '使用停止', exact: true })).toBeVisible()
  await expectNoAxeViolations(page)
  await dialog.getByRole('button', { name: 'キャンセル' }).click()
})

test('TC-363: 320px timing editor focuses validation and keeps staged-discard controls reachable', async ({ page }) => {
  await signIn(page); await page.setViewportSize({ width: 320, height: 844 })
  await page.goto('/production-lines/new')
  await page.getByLabel('ラインコード', { exact: true }).fill(`MOB-FORM-${Date.now()}`)
  await page.getByLabel('ライン名', { exact: true }).fill('モバイル編集')
  await page.getByLabel('稼働時間／日', { exact: true }).fill('24.001')
  await page.getByLabel('製品を検索', { exact: true }).fill('P-1001')
  await page.getByRole('button', { name: '検索', exact: true }).click()
  await expect(page.getByRole('button', { name: '製品を追加', exact: true })).toHaveCount(1)
  await page.getByRole('button', { name: '製品を追加', exact: true }).click()
  await page.getByLabel('生産時間 (分／1単位)', { exact: true }).fill('0.125')
  await page.getByLabel('表示単位で生産時間を確認しました').check()
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByLabel('稼働時間／日', { exact: true })).toBeFocused()
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false)
  await expectNoAxeViolations(page)
  await page.getByRole('link', { name: 'キャンセル', exact: true }).click()
  const modal = page.getByRole('dialog'); await expect(modal).toBeVisible()
  await expect(modal.getByRole('button', { name: 'キャンセル' })).toBeFocused()
  await expect(modal.getByRole('button', { name: '変更を破棄' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByLabel('生産時間 (分／1単位)')).toHaveValue('0.125')
})
